[lang]
prefix = "§b[RotMC] "
nopermission = "§cYou dont have permission to use Emojis!"
invalidcharprefix = "§cSpecial characters such as '"
invalidcharsuffix = "§c' are not allowed!"
emojilistheader = "            §6--§r §bList of Emojis§r §6--"
emojilisttutorialtext = "§cSimply type the Emoji Identifier into chat!"
